# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-proxy

PORTNAME=	libreSense-pkg-zabbix-proxy5

CONFLICTS=	libreSense-pkg-zabbix-proxy \
		libreSense-pkg-zabbix-proxy4 \
		libreSense-pkg-zabbix-proxy44 \
		libreSense-pkg-zabbix-proxy54 \
		libreSense-pkg-zabbix-proxy6 \
		libreSense-pkg-zabbix-proxy7

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix5-proxy

ZABBIXINTERNALNAME=	zabbix-proxy5
ZABBIXTITLE=	Zabbix Proxy 5.0
ZABBIXVERSION=	50

.include "${MASTERDIR}/Makefile"
