# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-proxy

PORTNAME=	libreSense-pkg-zabbix-proxy6

CONFLICTS=	libreSense-pkg-zabbix-proxy \
		libreSense-pkg-zabbix-proxy4 \
		libreSense-pkg-zabbix-proxy44 \
		libreSense-pkg-zabbix-proxy5 \
		libreSense-pkg-zabbix-proxy54 \
		libreSense-pkg-zabbix-proxy7

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix6-proxy

ZABBIXINTERNALNAME=	zabbix-proxy6
ZABBIXTITLE=	Zabbix Proxy 6
ZABBIXVERSION=	6

.include "${MASTERDIR}/Makefile"
