# $FreeBSD

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-agent

PORTNAME=	libreSense-pkg-zabbix-agent54

CONFLICTS=	libreSense-pkg-zabbix-agent \
		libreSense-pkg-zabbix-agent4 \
		libreSense-pkg-zabbix-agent44 \
		libreSense-pkg-zabbix-agent5 \
		libreSense-pkg-zabbix-agent6 \
		libreSense-pkg-zabbix-agent62 \
		libreSense-pkg-zabbix-agent7

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix54-agent

ZABBIXINTERNALNAME=	zabbix-agent54
ZABBIXTITLE=	Zabbix Agent 5.4
ZABBIXVERSION=	54

.include "${MASTERDIR}/Makefile"
