# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-proxy

PORTNAME=	libreSense-pkg-zabbix-proxy54

CONFLICTS=	libreSense-pkg-zabbix-proxy \
		libreSense-pkg-zabbix-proxy4 \
		libreSense-pkg-zabbix-proxy44 \
		libreSense-pkg-zabbix-proxy5 \
		libreSense-pkg-zabbix-proxy6 \
		libreSense-pkg-zabbix-proxy7

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix54-proxy

ZABBIXINTERNALNAME=	zabbix-proxy54
ZABBIXTITLE=	Zabbix Proxy 5.4
ZABBIXVERSION=	54

.include "${MASTERDIR}/Makefile"
