# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-proxy

PORTNAME=	libreSense-pkg-zabbix-proxy4

CONFLICTS=	libreSense-pkg-zabbix-proxy \
		libreSense-pkg-zabbix-proxy44 \
		libreSense-pkg-zabbix-proxy5 \
		libreSense-pkg-zabbix-proxy52

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix4-proxy

ZABBIXINTERNALNAME=	zabbix-proxy4
ZABBIXTITLE=	Zabbix Proxy 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
