# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-proxy

PORTNAME=	libreSense-pkg-zabbix-proxy7

CONFLICTS=
CONFLICTS+=	libreSense-pkg-zabbix-proxy
CONFLICTS+=	libreSense-pkg-zabbix-proxy4
CONFLICTS+=	libreSense-pkg-zabbix-proxy44
CONFLICTS+=	libreSense-pkg-zabbix-proxy5
CONFLICTS+=	libreSense-pkg-zabbix-proxy54
CONFLICTS+=	libreSense-pkg-zabbix-proxy6

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix7-proxy

ZABBIXINTERNALNAME=	zabbix-proxy7
ZABBIXTITLE=	Zabbix Proxy 7
ZABBIXVERSION=	7

PORTREVISION=	1

.include "${MASTERDIR}/Makefile"
