# $FreeBSD

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-agent

PORTNAME=	libreSense-pkg-zabbix-agent6

CONFLICTS=	libreSense-pkg-zabbix-agent \
		libreSense-pkg-zabbix-agent4 \
		libreSense-pkg-zabbix-agent44 \
		libreSense-pkg-zabbix-agent5 \
		libreSense-pkg-zabbix-agent54 \
		libreSense-pkg-zabbix-agent62 \
		libreSense-pkg-zabbix-agent7

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix6-agent

ZABBIXINTERNALNAME=	zabbix-agent6
ZABBIXTITLE=	Zabbix Agent 6
ZABBIXVERSION=	6

.include "${MASTERDIR}/Makefile"
