PORTNAME=	libreSense-ce
DISTVERSION=	${PRODUCT_VERSION}
CATEGORIES=	security

MAINTAINER=	coreteam@libresense.org
COMMENT=	libresense CE additional packages.
WWW=		https://www.libresense.org/

LICENSE=	APACHE20

RUN_DEPENDS=	drm-515-kmod>0:graphics/drm-515-kmod

USES=		metaport

.include <bsd.port.pre.mk>
.include <bsd.port.post.mk>
