# $FreeBSD$

MASTERDIR=	${.CURDIR}/../libreSense-pkg-zabbix-agent

PORTNAME=	libreSense-pkg-zabbix-agent4

CONFLICTS=	libreSense-pkg-zabbix-agent \
		libreSense-pkg-zabbix-agent44 \
		libreSense-pkg-zabbix-agent5 \
		libreSense-pkg-zabbix-agent52

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix4-agent

ZABBIXINTERNALNAME=	zabbix-agent4
ZABBIXTITLE=	Zabbix Agent 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
